name: build-deb
on:
  push:
  workflow_dispatch:

jobs:
  deb:
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          set -euxo pipefail
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y --no-install-recommends \
          devscripts build-essential fakeroot ca-certificates git \
          cmake ninja-build extra-cmake-modules pkg-kde-tools gettext \
          qt6-base-dev qt6-declarative-dev qt6-svg-dev \
          libplasma-dev libkf6i18n-dev libkf6notifications-dev libkf6package-dev

      - name: Build .deb
        env:
          DEB_BUILD_OPTIONS: parallel=$(nproc)
        run: |
          set -euxo pipefail
          dpkg-buildpackage -us -uc -b

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kfritz-trixie
          path: |
            ../*.deb
            ../*.changes
            ../*.buildinfo

      # Hilfreich, falls CMake nochmal scheitert
      - name: Dump CMakeError on failure
        if: failure()
        run: |
          set +e
          find .. -name CMakeError.log -print -exec sed -n '1,200p' {} \;
